language: python
python:
  - 3.9

env:
  -PIPENV_VENV_PROJECT=1
  -PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install -q pipenv codecov
  - pipenv sync --dev

script:
  - pipenv run flake8

after_success:
  - pipenv run codecov